[goldmark]
    [goldmark.renderer]
        unsafe = true
    [goldmark.parser.attribute]
        block = true
        title = true

[highlight]
    codeFences = true
    guessSyntax = true
    lineNos = false
    style = "monokai"
